In [7]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, features):

    out = self.network(features)

    return out

In [8]:
torch.rand(10,5)

tensor([[3.5745e-01, 3.1605e-01, 8.0001e-01, 9.6238e-01, 1.2691e-01],
        [7.0616e-01, 7.1193e-01, 7.7854e-01, 3.4297e-01, 3.2226e-01],
        [1.9728e-01, 9.3567e-01, 1.8799e-01, 5.4654e-01, 1.5803e-01],
        [1.4031e-01, 7.0387e-01, 6.5705e-01, 3.8770e-01, 3.8681e-02],
        [7.7621e-01, 5.1837e-01, 1.8663e-01, 3.3169e-01, 7.3218e-01],
        [6.2233e-01, 5.2211e-01, 9.1824e-01, 1.4192e-01, 4.9177e-01],
        [1.7819e-01, 6.4640e-01, 6.5040e-01, 6.1420e-03, 1.4191e-01],
        [8.0360e-01, 6.4681e-01, 7.8934e-04, 2.4131e-01, 5.5956e-01],
        [9.1457e-01, 7.5857e-01, 6.6189e-02, 1.2950e-01, 9.9891e-01],
        [9.6636e-01, 5.6602e-01, 5.6657e-01, 2.9510e-01, 7.4607e-01]])

In [9]:
features = torch.rand(10,5)

In [10]:
features.shape[1]

5

In [11]:
# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call model for forward pass
# model.forward(features)
model(features)

tensor([[0.5454],
        [0.5379],
        [0.5257],
        [0.5491],
        [0.5337],
        [0.5556],
        [0.5399],
        [0.5428],
        [0.5143],
        [0.5401]], grad_fn=<SigmoidBackward0>)

In [14]:
# show model weights
model.network[0].weight

Parameter containing:
tensor([[-0.0883,  0.0563,  0.0141,  0.2816, -0.4435],
        [ 0.3008, -0.2978, -0.0758,  0.1809, -0.0427],
        [ 0.2058, -0.4099, -0.4347, -0.3015, -0.3678]], requires_grad=True)

In [16]:
# show model weights
model.network[0].weight

Parameter containing:
tensor([[-0.0883,  0.0563,  0.0141,  0.2816, -0.4435],
        [ 0.3008, -0.2978, -0.0758,  0.1809, -0.0427],
        [ 0.2058, -0.4099, -0.4347, -0.3015, -0.3678]], requires_grad=True)

In [13]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00